version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8112:8112"
    environment:
      - DB_URL=postgresql://polak_user:polak_password@db:5432/polak_db
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=polak_user
      - POSTGRES_PASSWORD=polak_password
      - POSTGRES_DB=polak_db

volumes:
  postgres_data:
