FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.8.2 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc curl\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - 
RUN ln -s /root/.local/bin/poetry /usr/local/bin/poetry
RUN poetry self update

COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN poetry sync --without dev --no-root

COPY polak ./polak

# Expose port
EXPOSE 8112

# Command to run the application
CMD ["uvicorn", "polak.main:app", "--host", "0.0.0.0", "--port", "8112"]
